### ISSUE TITLE
Named parameter should not take precedence on defined route

### ISSUE THREAD

**Issue by vinerz** [alexmingoia/koa-router#157] opened 2015-07-31 08:26 UTC
Hello everyone. I am having a big issue here because my root route is able to receive IDs of objects directly on it, like **api.com/2039238**. The problem came when I added another route named **/search**. The root route with the named parameter **:id** *always* takes precedence. For example, the simple code below outputs **You are on route :name** even if you access **localhost:3000/hello**.

```js
"use strict";

// Dependencies
var koa   = require('koa');
var Router = require('koa-router');

// Main Elements
var router = new Router();
var app = koa();

// Routes
router.get('/:name', function *(next) {
    this.body = 'You are on route :name';

    yield next;
});

router.get('/hello', function *(next) {
    this.body = 'You are on route hello';

    yield next;
});

// Apply Routes
app.use(router.routes());

// Start
app.listen(3000);
```

**Comment by neVERberleRfellerER** [comment] 2015-08-05 23:59
Change order:
router.get('/hello',...
router.get('/:name',...

**Comment by Tankenstein** [comment] 2015-10-02 06:32
This is implemented in the newest version, however, if you want to set body on a route (and have it stay there), you should not be yielding next.

**Comment by dvlsg** [comment] 2015-10-23 23:41
Possibly related question. Given this router setup:

```js
router.get('/notparameter', function *(next) {
    yield next;
});

router.get('/:parameter', function *(next) {
    this.body = {
        test: 'foo'
    };
});
```

Making a get request to `/notparameter` will end up inside the generator for `/:parameter` due to the `yield next`. It looks like it is treating the generator with `/:parameter` as middleware for `/notparameter`. Is this expected behavior?

Using koa-router 5.2.3 to get the result above.

**Comment by gimre** [comment] 2015-12-01 00:25
hey, ran into the same issue as here, but I need to yield next from all route handlers if I want to use any other middleware downstream of koa-router :( suggestions?

**Comment by alexmingoia** [comment] 2016-02-11 20:03
Closing this as it's continued in #231

**Closed by alexmingoia** 2016-02-11 20:03 UTC
Labels: bug, enhancement
