### ISSUE TITLE
promise / async in experimental mode doesn't work properly

### ISSUE THREAD

**Issue by mgreschke** [alexmingoia/koa-router#240] opened 2016-02-11 22:03 UTC
Hi everyone,

the functionality outlined in the unit tests via:

```
  it('supports promises for async/await', function (done) {
    var app = new Koa();
    app.experimental = true;
    var router = Router();
    router.get('/async', function (ctx, next) {
      return new Promise(function (resolve, reject) {
        ctx.body = {
          msg: 'promises!'
        };
        resolve();
      });
    });
```

doesn't work for me as soon as there is an actual async delay in there.
e.g. this would return a 404:

```
router.get(p, function (ctx, next) {
        return new Promise(function (resolve, reject) {
            setTimeout(() => {
            ctx.body = 'test';
            resolve();
            }, 100)
        });
});
```

If I remove the setTimeout it however works just fine.
Am I misunderstanding something or is this not working in the latest version?

I enabled experimental mode.

Cheers

**Comment by jbielick** [comment] 2016-02-12 00:24
@mgreschke Hey!

Do you think you could reproduce what you're seeing in a small, portable script so we can run it ourselves? 

Also, could you list the exact version of koa, node and koa-router that you're using in your example?

I put together a small server quickly with the following:

`node@5.0.0`
`koa-router@7.0.1`
`koa@2.0.0-alpha.3`

package.json:
```
{
  "name": "koa-router-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "koa": "2.0.0-alpha.3",
    "koa-router": "7.0.1"
  }
}
```

app.js:
```javascript
var koa = require('koa');
var app = new koa();
var router = require('koa-router')();

app.experimental = true;

router.get('/', function (ctx, next) {
  return new Promise(function(resolve, reject) {
    setTimeout(function() {
      ctx.body = 'Hi there';
      resolve();
    }, 1000);
  });
});

app
  .use(router.routes())
  .use(router.allowedMethods());

app.listen(8081);
```

And when running the server, it takes approximately 1 second to respond as simulated with the `setTimeout`. I have also added a setTimeout to the test example you're referring to and the tests still pass with any value for the delay.

```
┌[josh@HAL9000] [7]
└[~]> time curl localhost:8081
Hi there
curl localhost:8081  0.00s user 0.00s system 0% cpu 1.029 total
```

Maybe we can figure out what's going wrong when you share the version details of your project

**Comment by mgreschke** [comment] 2016-02-12 08:41
Hi @jbielick !

Thanks for the swift response.

This is my version set:
```
    node 5.5.0
    "koa": "^2.0.0-alpha.3",
    "koa-bodyparser": "^3.0.0",
    "koa-helmet": "^2.0.0-alpha.1",
    "koa-router": "^7.0.1",
```

Your test app worked for me and I was also able to make it work for myself. I had a slight misunderstanding about how middleware works in koa@next.

The problem was a middleware like this:

```
app.use((ctx, next) => {
    ctx.state.language = 'test';
    ctx.state.country = 'test';
   next();
});
``

When using ```return next();``` instead of ```next();``` it works like a charm.

Maybe this is something that could be updated in the documentation on the new alpha. Having the next argument is pretty inviting to use like in a classic callback framework. This couldn't really happen in the previous koa version because the generators forced a different mental model to begin with.

Anyhow, thanks a lot for your help!

Cheers

**Comment by jbielick** [comment] 2016-02-12 15:52
> This couldn't really happen in the previous koa version because the generators forced a different mental model to begin with.

Totally. The implicit continuation of generators in the middleware chain after they return was nice, but since koa2 is essentially promise-based, a thenable has be returned from each middleware in order for the `next` to be called after the returned promise. It's really easy to miss! 

I'll see if we can add a clearer example do the docs and tests so that this isn't as confusing!

**Comment by sanketmeghani** [comment] 2017-07-05 11:13
I am running into a issue related to this: I have following code snippet,
    const app = new Koa();
    app.experimental = true;
    const router = new Router();
    
    router.get('/signin', (ctx, next) => {
   
        const myPromise = new Promise((resolve, reject) => {
            setTimeout(() => resolve('Resolved'), 5000); //It works if I comment this line and un-comment following line
            // resolve('Resolved');
        });

        myPromise.then((result) => {
            ctx.response.type = 'text/html';
            ctx.response.body = 'Success';
            return next();
        });

        return myPromise;
    });

    app.use(router.routes());
    app.use(router.allowedMethods());

The request never returns and it waits for ever. If I remove the delay before resolving promise, it returns the 'Success'.

`curl http://localhost:3000/signin`

I am using koa@^2.2.0, koa-router@^7.2.1 on node@6.9.1. Any idea what am I missing?

**Comment by sanketmeghani** [comment] 2017-07-05 11:56
On further debugging, it seems the issue occurs when koa-webpack-middleware is used. If I remove devMiddleware & hotMiddleware from koa-webpack-middleware then above code works as expected. May be it is an issue with koa-webpack-middleware.

**Closed** 2017-07-10 15:56 UTC
