### ISSUE TITLE
Npm install incompatible version by default

### ISSUE THREAD

**Issue by pensierinmusica** [alexmingoia/koa-router#327] opened 2017-01-30 02:15 UTC
Hi,

At the time of this writing, `npm install koa` by default installs Koa `v1.2.4`.

Unfortunately  though `npm install koa-router` by default installs `v7.0.1` of the router, which is meant for Koa `v2.x` and is incompatible with `v1.x`.

Can you please check and fix it?

Thanks!

**Comment by ztrange** [comment] 2017-01-30 19:37
This is a dupe of #324

**Comment by alexmingoia** [comment] 2017-02-06 18:05
```sh
npm dist-tag ls koa-router
latest: 5.4.0
next: 7.0.1
```

**Closed by alexmingoia** 2017-02-06 18:05 UTC
